### ISSUE TITLE
OCTGN IDs?

### ISSUE THREAD

**Issue by brine** [Alsciende/fiveringsdb-data#27]
If there's interest in adding an OCTGN deck export option (similar to thronesdb), I can go through and add in the existing IDs for the cards into the database.

**Comment by Alsciende** [comment]
I haven't had many requests for an OCTGN export, and I'm not in a hurry to add export options to the site. If there's a need for such an option, I would add the octgn IDs to the cards, but I wouldn't implement an OCTGN export feature. The OCTGN IDs would be exported with the deck contents at the API level, and we would need a thrid-party tool to convert such json data into a proper OCTGN deck.

**Comment by brine** [comment]
that's a good idea -- my group can look into writing an OCTGN deck editor plugin to read the json data and convert that to an OCTGN deck.  We can probably extend such a plugin to work with thronesdb and the other deckbuilders as well, assuming the json data is exported in the same format.

**Comment by Alsciende** [comment]
Ok then. If you can submit a PR with an `octgn_id` value for each CardPack (or Card, as you see fit), I'll update the code to read and use it.

**Comment by brine** [comment]
The decks themselves don't retain individual printings from PackCard, correct?  From a data perspective it makes sense for the IDs to go into PackCard data as each physical printing/release of a card would have its own OCTGN GUID assigned in its set definition file.

If the deck editor doesn't interpret any of the PackCard data then I'll have to think of a better way to approach this.

**Comment by Alsciende** [comment]
That's correct: the decks don't know which packs the cards come from.
