### ISSUE TITLE
Swapping Role cards & deck validation

### ISSUE THREAD

**Issue by Saelvarath** [Alsciende/fiveringsdb-data#42]
I had previously made a Dragon deck on FiveRingsDB with a copy of the Stone of Sorrows (Seeker only) card included.
When updating the deck with some cards from DotV I swapped my role from Seeker of Fire to Support of the Phoenix.
The deck validator didn't catch that I still had Seeker Only cards in my deck and counted the deck as Valid.

That's the main issue but a small gripe I have is that to remove the Stone of Sorrows from the deck I had to swap Roles back to a Seeker to be able to even see the card in the builder interface.

**Comment by Alsciende** [comment]
Thanks for the report. 

I'll fix the validator so that it checks role-restricted cards.

If the Stone of Sorrows stayed in the list but marked in red, would that be better?

**Comment by Saelvarath** [comment]
That would be much better!

**Comment by Fuzzylog1cza** [comment]
Hi @Saelvarath , do you know if this particular issue was ever resolved?

**Comment by Saelvarath** [comment]
I think it might have been? I can't say for sure.

I fell out of the game many months ago and haven't had the time or energy
get back into it so I haven't even visited the site in ages.

Sorry.
