### ISSUE TITLE
minimal working dev dist

### ISSUE THREAD

**Issue by jrekier** [Alsciende/fiveringsdb-data#44]
Hi Alsciende,

What would be the minimal setup for a local installation ? 
My friends and I would like to use fiveringsdb with custom cards.

**Comment by Fuzzylog1cza** [comment]
Hi @jrekier, we've stepped up as additional contributors for this repo.

With regards to your question, can you provide more information about what you are looking for? E.g. is it a setup and install guide or is it more detail like how to use the server app and vue client?

**Comment by jrekier** [comment]
Hi @Fuzzylog1cza, thanks for the response.
A guide for a local installation would be grand.

**Comment by Fuzzylog1cza** [comment]
Hi @jrekier , the full application is actually across 3 repositories. If you want to get started on a local setup see https://github.com/Alsciende/fiveringsdb-api/blob/master/README.md for the steps.

I suggest looking at https://laravel.com/docs/5.7/homestead for how to get a full LAMP stack setup via VM.
