### ISSUE TITLE
Card error

### ISSUE THREAD

**Issue by UtakuNakata** [Alsciende/fiveringsdb-data#95]
On the card text from Ide Negociator from Children of the Empire :

Reaction: After you reveal your honor dial - change the bid on your dial to a value 1 higher or lower than its current value (to a minimum of 0 and a maximum to 5).

It should be "to a minimum of 1 and a maximum of 5".

Cheers,

**Comment by xWorkerBeex** [comment]
Thanks for reporting :)

The issue has already been resolved in #91 but the changes are not live yet. As soon as the Database gets restarted, Ide Negotiator will have the correct ability text.

**Comment by Fuzzylog1cza** [comment]
I've pulled the latest data and updated the DB. This issue is now resolved.
